### ISSUE TITLE
"Cannot read property 'location' of null" error in javascript

### ISSUE THREAD

**Issue by guillehorno** [intercom/intercom-rails#244]
Hi. I've recently integrated javascript error reporting and started to see some exceptions from the intercom javascript script. The error comes from https://js.intercomcdn.com/frame.2f08db79.js , line 24 column 701. It's the definition of the function _getCurrentPage

``
r.prototype._getCurrentPage=function(){return window.location.href}
``

I'm not sure if this is normal, looks like in the context of the execution of this function window is undefined.

This is the complete stack trace:

```
File https://js.intercomcdn.com/frame.2f08db79.js line 24 col 701 in r._getCurrentPage
File https://js.intercomcdn.com/frame.2f08db79.js line 23 col 31744 in r._sendUserPresenceEvent
File https://js.intercomcdn.com/frame.2f08db79.js line 23 col 31549 in r._userPresence
File https://js.intercomcdn.com/frame.2f08db79.js line 23 col 30925 in r.setUserPresent
File https://js.intercomcdn.com/frame.2f08db79.js line 17 col 13232 in [anonymous]
File https://js.intercomcdn.com/frame.2f08db79.js line 17 col 4198 in [anonymous]
File https://js.intercomcdn.com/frame.2f08db79.js line 17 col 12460 in [anonymous]
File https://js.intercomcdn.com/frame.2f08db79.js line 29 col 5518 in [anonymous]
File https://js.intercomcdn.com/frame.2f08db79.js line 5 col 16073 in onUserPresent
File https://js.intercomcdn.com/frame.2f08db79.js line 17 col 16044 in l
File https://js.intercomcdn.com/frame.2f08db79.js line 17 col 16160 in HTMLDocument.h
```

Thanks!

## Version info
  - intercom-rails version: 0.3.4
  - Rails version: 5.0.1

**Comment by savmac** [comment]
I am getting the same error in the chrome console: 
`Uncaught TypeError: Cannot read property 'location' of null`

I've narrowed it down to intercom and turbolinks (latest version 5.0.1) not working together, specifically when the browser's back or forward button is used and turbolinks is rendering from cache.

**Comment by buffym** [comment]
@savmac I tried your workaround and I'm still receiving the location null error. Did placement compared to other javascript (if any) in the head matter?

**Comment by nachomazzara** [comment]
+1 I'm having the same issue.

**Comment by savmac** [comment]
@buffym Is your project using Turbolinks? In my case it appeared as a conflict with Turbolinks since it only renders the body and not the head after the initial page load. All of my scripts were in the head except for Intercom's because of it's automatic insertion into the body which I didn't realize until I saw this error.

If you are not using turbolinks then it may be a different issue causing the error.

I'm not that great with javascript so I'm not really sure how to investigate it further. It could be similar to [this pull request](https://github.com/intercom/intercom-rails/pull/215) except fix it for the latest version of turbolinks. Maybe someone from the Intercom team can check it out?

**Comment by buffym** [comment]
@savmac I am using Turbolinks. I load most of my page javascript before the closing body tag, and use "data-turbolinks-eval=false" to prevent Turbolinks from reloading it when it swaps things around.

**Comment by nachomazzara** [comment]
I'm not using turbolinks and error is still there

**Comment by savmac** [comment]
In case it helps the investigation, I just checked my history and initially I was using the latest version of turbolinks and definitely did not have this error. Weeks later I updated the intercom-rails gem from 0.2.30 to 0.3.4 and subsequently discovered this error.

**Comment by buffym** [comment]
Thanks @savmac I'll look into rolling back my intercom-rails version (for now) and see if that helps.

**Comment by scottsouthard** [comment]
Got a customer running into this here:
https://intercomrades.intercom.com/a/apps/tx2p130c/inbox/scott.southard@intercom.io/conversations/8611489973

**Comment by filipeperdigaosousa** [comment]
I'm still having this error. There is a way to solve it?

**Comment by volkanunsal** [comment]
Is there any chance this will get fixed? I'm getting dozens of errors everyday from this library.

**Comment by jfeust** [comment]
Bump on this. Can we please get this resolved?  We're using Rails 5, Turbolinks 5, with `turbolinks-cache-control` set to `no-cache`. 

Dozens+ of these errors every day.

**Comment by Skaelv** [comment]
This should be fixed now. Can you confirm you don't see any `Uncaught TypeError: Cannot read property 'location' of null` anymore?

**Comment by filipeperdigaosousa** [comment]
This error has disapeard, but right now, I'm experiencing tons of  `undefined is not an object (evaluating 'e.userAgent')`

**Comment by Skaelv** [comment]
I see you created another [issue](https://github.com/intercom/intercom-rails/issues/262) for this new problem. I'll close this issue as it it fixed.

**Comment by rubendinho** [comment]
@Skaelv - We are persistently seeing this error on production, and have been for close to a year. It seems to come and go - most recently it's affecting Chrome users on both Android and Windows. 

We are running. 
rails 5.1.4
turbolinks 5.0.3
intercom-rails 0.3.5

**Comment by giolazzareschi** [comment]
Hi!

I'm still having this issue. Idk the root cause but I manage to correct it just doing

try{Intercom("shutdown")}catch(e){}

before leave the page.

Maybe it could help yours too.

Regards.

**Comment by giolazzareschi** [comment]
Hi!

As the Turbolinks change pages we need update intercom before.

I could manage a workaround just playing "update" method right after boot it.

```
function renderIntercom() {
	try{Intercom("shutdown")}catch(e){};
	Intercom('boot', {  
		app_id: 'APP_ID',
		email: 'john.doe@example.com',
		created_at: +new Date,
		name: 'John Doe'
	});
	window.Intercom("update");
}

´´´

Hope it helps someone.
